version: '3'
services: 
  segmentation_task: 
    image: segmentation_task
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - "../:/src/segmentation_task"